# Generated by Django 4.1.3 on 2022-11-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
