# Generated by Django 4.1.3 on 2022-11-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
