# Generated by Django 4.1.3 on 2022-11-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_candidate_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=100, null=True),
        ),
    ]
