# Generated by Django 4.1.3 on 2022-11-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_candidate_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gneder',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='personality',
            field=models.CharField(choices=[('', 'Select your personality'), ('I am Outgoing', 'I am Outgoing'), ('I am Sociable', 'I am Sociable'), ('I am Antisociable', 'I am Antisociable'), ('I am Discreet', 'I am Discreet'), ('I am Seriou', 'I am Seriou')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='smoker',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='', max_length=10, null=True),
        ),
    ]
