# Generated by Django 4.1.3 on 2022-11-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_candidate_experience_candidate_gneder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='gneder',
            new_name='gender',
        ),
    ]
