# Generated by Django 4.1.3 on 2022-11-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_candidate_file_alter_candidate_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
