# Generated by Django 4.1.3 on 2022-11-12 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_candidate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='file',
            field=models.FileField(default=datetime.datetime(2022, 11, 12, 9, 41, 14, 404253, tzinfo=datetime.timezone.utc), upload_to=''),
            preserve_default=False,
        ),
    ]
