# Generated by Django 4.1.3 on 2022-11-12 12:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_candidate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='frameworks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Angular', 'Angular'), ('Dango', 'Dango'), ('Flask', 'Flask'), ('Vue', 'Vue'), ('Others', 'Others')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='personality',
            field=models.CharField(choices=[('', 'Select your personality'), ('I am Outgoing', 'I am Outgoing'), ('I am Sociable', 'I am Sociable'), ('I am Antisociable', 'I am Antisociable'), ('I am Discreet', 'I am Discreet'), ('I am Seriou', 'I am Seriou')], max_length=50, null=True),
        ),
    ]
