# Generated by Django 4.1.3 on 2022-11-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_candidate_databases_candidate_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='company_note',
            field=models.TextField(blank=True),
        ),
    ]
