# Generated by Django 4.1.3 on 2022-11-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_candidate_company_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='age',
        ),
        migrations.AddField(
            model_name='candidate',
            name='birth',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
    ]
