# Generated by Django 4.1.3 on 2022-11-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_candidate_age_candidate_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='about_course',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='about_job',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='course',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='employed',
            field=models.BooleanField(null=True, verbose_name='I am employed .'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='finished_course',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='finished_job',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='institution',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='remote',
            field=models.BooleanField(null=True, verbose_name='I agree to work remotly'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='started_course',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='started_job',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status_course',
            field=models.CharField(choices=[('', 'Select your status'), ('Studying', 'Studying'), ('Break', 'Break'), ('Completed', 'Completed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='travel',
            field=models.BooleanField(null=True, verbose_name="I'm available for travel"),
        ),
    ]
